package com.ccsna.safetynet.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

/**
 * Agency generated by hbm2java
 */
public class Agency implements java.io.Serializable {

    private Integer agencyId;
    private String fullname;
    private String streetAddress;
    private String apartmentNo;
    private String city;
    private String state;
    private Long zipcode;
    private Long privateContactNumber;
    private Long publicContactNumber;
    private String websiteAddress;
    private Date dateCreated;
    private String createdBy;
    private Date dateUpdated;
    private String updatedBy;
    private String mission;
    private String countiesServed;
    private Set counties = new HashSet(0);
    private Set members = new HashSet(0);
    private Set serviceses = new HashSet(0);
    private String hoursOfOperation;
    private String requiredVerification;
    private String boardPositions;
    private String status;
    private String emailAddress;

    public Agency() {
    }


    public Agency(String fullname, String streetAddress, String apartmentNo, String city, String state, Long zipcode, Long privateContactNumber, String websiteAddress, Date dateCreated, String createdBy, String mission, String hoursOfPositions, String requiredVerification, String boardPositions, String status, Long publicContactNumber, String emailAddress) {
        this.fullname = fullname;
        this.streetAddress = streetAddress;
        this.apartmentNo = apartmentNo;
        this.city = city;
        this.state = state;
        this.zipcode = zipcode;
        this.privateContactNumber = privateContactNumber;
        this.websiteAddress = websiteAddress;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
        this.mission = mission;
        this.boardPositions = boardPositions;
        this.hoursOfOperation = hoursOfPositions;
        this.requiredVerification = requiredVerification;
        this.status = status;
        this.publicContactNumber = publicContactNumber;
        this.emailAddress = emailAddress;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "agency_ID")
    public Integer getAgencyId() {
        return this.agencyId;
    }

    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getStreetAddress() {
        return this.streetAddress;
    }

    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    public String getApartmentNo() {
        return this.apartmentNo;
    }

    public void setApartmentNo(String apartmentNo) {
        this.apartmentNo = apartmentNo;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Long getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(Long zipcode) {
        this.zipcode = zipcode;
    }

    public String getWebsiteAddress() {
        return this.websiteAddress;
    }

    public void setWebsiteAddress(String websiteAddress) {
        this.websiteAddress = websiteAddress;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getMission() {
        return this.mission;
    }

    public void setMission(String mission) {
        this.mission = mission;
    }

    /*public String getCountiesServed() {
        return this.countiesServed;
    }

    public void setCountiesServed(String countiesServed) {
        this.countiesServed = countiesServed;
    }*/
    
    @ManyToMany
    @JoinTable(name = "AgencyCountyServed",
            joinColumns = {@JoinColumn(name = "Agency_ID" )},
            inverseJoinColumns = {@JoinColumn(name = "County_ID")}
    )      
    public Set getCounties() {
        return this.counties;
    }

    public void setCounties(Set counties) {
        this.counties = counties;
    }

    public Set getMembers() {
        return this.members;
    }

    public void setMembers(Set members) {
        this.members = members;
    }

    public Set getServiceses() {
        return this.serviceses;
    }

    public void setServiceses(Set serviceses) {
        this.serviceses = serviceses;
    }

    /**
     * @return the hoursOfOperation
     */
    public String getHoursOfOperation() {
        return hoursOfOperation;
    }

    /**
     * @param hoursOfOperation the hoursOfOperation to set
     */
    public void setHoursOfOperation(String hoursOfOperation) {
        this.hoursOfOperation = hoursOfOperation;
    }

    /**
     * @return the requiredVerification
     */
    public String getRequiredVerification() {
        return requiredVerification;
    }

    /**
     * @param requiredVerification the requiredVerification to set
     */
    public void setRequiredVerification(String requiredVerification) {
        this.requiredVerification = requiredVerification;
    }

    /**
     * @return the boardPositions
     */
    public String getBoardPositions() {
        return boardPositions;
    }

    /**
     * @param boardPositions the boardPositions to set
     */
    public void setBoardPositions(String boardPositions) {
        this.boardPositions = boardPositions;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * @return the privateContactNumber
     */
    public Long getPrivateContactNumber() {
        return privateContactNumber;
    }

    /**
     * @param privateContactNumber the privateContactNumber to set
     */
    public void setPrivateContactNumber(Long privateContactNumber) {
        this.privateContactNumber = privateContactNumber;
    }

    /**
     * @return the publicContactNumber
     */
    public Long getPublicContactNumber() {
        return publicContactNumber;
    }

    /**
     * @param publicContactNumber the publicContactNumber to set
     */
    public void setPublicContactNumber(Long publicContactNumber) {
        this.publicContactNumber = publicContactNumber;
    }

    /**
     * @return the emailAdddress
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * @param emailAddress the emailAdddress to set
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

}
