package com.ccsna.safetynet.model;
// Generated Oct 20, 2015 4:22:25 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.ManyToMany;

/**
 * County generated by hbm2java
 */
public class County  implements java.io.Serializable {


     private int idCounty;
     private Set agencies = new HashSet(0);
     private String countyName;

    public County() {
    }

	
    public County(int idCounty) {
        this.idCounty = idCounty;
    }
    public County(int idCounty, Set agencies) {
       this.idCounty = idCounty;
       this.agencies = agencies;
    }
   
    public int getIdCounty() {
        return this.idCounty;
    }
    
    public void setIdCounty(int idCounty) {
        this.idCounty = idCounty;
    }
    @ManyToMany(mappedBy = "counties")
    public Set getAgencies() {
        return this.agencies;
    }
    
    public void setAgencies(Set agencies) {
        this.agencies = agencies;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!this.getClass().equals(obj.getClass())) {
            return false;
        }

        County obj2 = (County) obj;
        return (Objects.equals(this.idCounty, obj2.getIdCounty())) && (this.countyName.equals(obj2.getCountyName()));
    }

    @Override
    public int hashCode() {
        int tmp = 0;
        tmp = (idCounty + countyName).hashCode();
        return tmp;
    }

    /**
     * @return the countyName
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * @param countyName the countyName to set
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }


}


