package com.ccsna.safetynet.model;
// Generated Oct 20, 2015 4:22:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

    private String username;
    private Agency agency;
    private String password;
    private String lastName;
    private String firstName;
    private String emailAddress;
    private Long phoneNumber;
    private String role;
   /* private String streetAddress;
    private String apartmentNo;
    private String city;
    private String state;
    private Long zipcode;
    private String county;*/
    private Date dateCreated;
    private String createdBy;
    private Date dateUpdated;
    private String updatedBy;
    private String title;
    private int memberId;
    private String status;

    public Member() {
    }

    public Member(String username, Agency agency, String password, String lastName, String firstName, String title, String role, Long phoneNumber, String createdBy, Date dateCreated, String status) {
        this.username = username;
        this.agency = agency;
        this.password = password;
        this.lastName = lastName;
        this.firstName = firstName;
        this.title = title;
        this.role = role;
        this.emailAddress = username;
        this.phoneNumber = phoneNumber;
        this.createdBy = createdBy;
        this.dateCreated = dateCreated;
        this.status = status;
    }

    public Member(String username, Agency agency, String password, String lastName, String firstName, String emailAddress, Long phoneNumber, String role, String streetAddress, String apartmentNo, String city, String state, Long zipcode, String county, Date dateCreated, String createdBy, String title) {
        this.username = username;
        this.agency = agency;
        this.password = password;
        this.lastName = lastName;
        this.firstName = firstName;
        this.emailAddress = emailAddress;
        this.phoneNumber = phoneNumber;
        this.role = role;
       /* this.streetAddress = streetAddress;
        this.apartmentNo = apartmentNo;
        this.city = city;
        this.state = state;
        this.zipcode = zipcode;
        this.county = county;*/
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
        this.title = title;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Agency getAgency() {
        return this.agency;
    }

    public void setAgency(Agency agency) {
        this.agency = agency;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public Long getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

   /* public String getStreetAddress() {
        return this.streetAddress;
    }

    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    public String getApartmentNo() {
        return this.apartmentNo;
    }

    public void setApartmentNo(String apartmentNo) {
        this.apartmentNo = apartmentNo;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Long getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(Long zipcode) {
        this.zipcode = zipcode;
    }

    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }
*/
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @return the memberId
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "memberID")
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * @param memberId the memberId to set
     */
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

}
