package com.ccsna.safetynet.model;
// Generated Oct 20, 2015 4:22:25 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private Integer newsId;
     private String title;
     private String newsType;
     private String content;
     private Date startDate;
     private Date endDate;
     private Date dateCreated;
     private String createdBy;
     private Date dateUpdated;
     private String updatedBy;
     private String status;
     private byte[] attachment;
     private String large_File_Name;
     private String file_Type;

    public News() {
    }

    public News(String title, String newsType, String content, Date startDate, Date endDate, Date dateCreated, String createdBy,String status, String largeFileName, String fileType) {
       this.title = title;
       this.newsType = newsType;
       this.content = content;
       this.startDate = startDate;
       this.endDate = endDate;
       this.dateCreated = dateCreated;
       this.createdBy = createdBy;
       this.status = status;
       this.large_File_Name = largeFileName;
       this.file_Type = fileType;
       
    }
    
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="news_ID")
    public Integer getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getNewsType() {
        return this.newsType;
    }
    
    public void setNewsType(String newsType) {
        this.newsType = newsType;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * @return the attachment
     */
    public byte[] getAttachment() {
        return attachment;
    }

    /**
     * @param attachment the attachment to set
     */
    public void setAttachment(byte[] attachment) {
        this.attachment = attachment;
    }

   

    /**
     * @return the large_File_Name
     */
    public String getLarge_File_Name() {
        return large_File_Name;
    }

    /**
     * @param large_File_Name the large_File_Name to set
     */
    public void setLarge_File_Name(String large_File_Name) {
        this.large_File_Name = large_File_Name;
    }

    /**
     * @return the file_Type
     */
    public String getFile_Type() {
        return file_Type;
    }

    /**
     * @param file_Type the file_Type to set
     */
    public void setFile_Type(String file_Type) {
        this.file_Type = file_Type;
    }



}


