package com.ccsna.safetynet.model;
// Generated Oct 20, 2015 4:22:25 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Services generated by hbm2java
 */
public class Services implements java.io.Serializable {

    private Integer serviceId;
    private String serviceName;
    private Date dateCreated;
    private String createdBy;
    private Date dateUpdated;
    private String updatedBy;
    private Set agencies = new HashSet(0);
    private String service_Type ;

    public Services() {
    }

    public Services(String serviceName) {
        this.serviceName = serviceName;
    }

    public Services(String serviceName, Date dateCreated, String createdBy, Date dateUpdated, String updatedBy, Set agencies, String serviceType) {
        this.serviceName = serviceName;
        this.dateCreated = dateCreated;
        this.createdBy = createdBy;
        this.dateUpdated = dateUpdated;
        this.updatedBy = updatedBy;
        this.agencies = agencies;
        this.service_Type = serviceType;
    }
    
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="service_ID")
    public Integer getServiceId() {
        return this.serviceId;
    }
    
    
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    public String getServiceName() {
        return this.serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getDateUpdated() {
        return this.dateUpdated;
    }

    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Set getAgencies() {
        return this.agencies;
    }

    public void setAgencies(Set agencies) {
        this.agencies = agencies;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!this.getClass().equals(obj.getClass())) {
            return false;
        }

        Services obj2 = (Services) obj;
        return (Objects.equals(this.serviceId, obj2.getServiceId())) && (this.serviceName.equals(obj2.getServiceName()));
    }

    @Override
    public int hashCode() {
        int tmp = 0;
        tmp = (serviceId + serviceName).hashCode();
        return tmp;
    }

    /**
     * @return the service_Type
     */
    public String getService_Type() {
        return service_Type;
    }

    /**
     * @param service_Type the service_Type to set
     */
    public void setService_Type(String service_Type) {
        this.service_Type = service_Type;
    }

}
